---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "Nicholas Bastian"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

### Introduction

_THIS `.qmd` IS INSTRUCTIONAL AND SHOULD `NOT` BE USED TO WRITE YOUR REPORTS (EXCEPTION - PROJECT 0). THERE IS ANOTHER TEMPLATE FILE FOR THAT. YOU WILL NEED TO `PREVIEW` THE REPORT TO PRODUCE A `.html` FILE. YOU WILL SUBMIT THE `.html` FILE ON CANVAS._

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
from palmerpenguins import load_penguins
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Elevator pitch
This project takes publically available data on penguin flipper length and body mass, so that we can visually observe if there is a correlation in flipper size to body mass.

```{python}
#| label: project-data
#| code-summary: Read and format project data

# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/mpg/mpg.csv")
```

__Highlight the Questions and Tasks__

## Question|TASK 1

Recreate the example chart from PY4DS: CH2 Data Visualization of the textbook.

This chart shows the relation of Flipper Length in millimeters to penguin Body mass measured in grams.

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
penguins = load_penguins()
penguins.head()
```

## Question|TASK 2

Include the table created from PY4DS: CH2 Data Visualization used to create the above chart

The chart above when graphed, shows that an increase in penguin flipper size correlates with a increase in penguin body mass.

```{python}
#| label: Q1-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here

(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)
```
